// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S1P2.DAL;

#nullable disable

namespace S1P2.Migrations
{
    [DbContext(typeof(AnimalContext))]
    partial class AnimalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.29");

            modelBuilder.Entity("S1P2.BL.Classes.Chicken", b =>
                {
                    b.Property<string>("RFID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EggsLaidPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatherColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RFID");

                    b.ToTable("Chickens");
                });

            modelBuilder.Entity("S1P2.BL.Classes.Cow", b =>
                {
                    b.Property<string>("RFID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BreedType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MilkProductionLitre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RFID");

                    b.ToTable("Cows");
                });
#pragma warning restore 612, 618
        }
    }
}
